/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { APIBUSINESSPARTNERASupplierCompanyTextTypeCreate } from './APIBUSINESSPARTNERASupplierCompanyTextTypeCreate';
import {
    APIBUSINESSPARTNERASupplierCompanyTextTypeCreateFromJSON,
    APIBUSINESSPARTNERASupplierCompanyTextTypeCreateFromJSONTyped,
    APIBUSINESSPARTNERASupplierCompanyTextTypeCreateToJSON,
} from './APIBUSINESSPARTNERASupplierCompanyTextTypeCreate';
import type { APIBUSINESSPARTNERASupplierDunningTypeCreate } from './APIBUSINESSPARTNERASupplierDunningTypeCreate';
import {
    APIBUSINESSPARTNERASupplierDunningTypeCreateFromJSON,
    APIBUSINESSPARTNERASupplierDunningTypeCreateFromJSONTyped,
    APIBUSINESSPARTNERASupplierDunningTypeCreateToJSON,
} from './APIBUSINESSPARTNERASupplierDunningTypeCreate';
import type { APIBUSINESSPARTNERASupplierTypeCreate } from './APIBUSINESSPARTNERASupplierTypeCreate';
import {
    APIBUSINESSPARTNERASupplierTypeCreateFromJSON,
    APIBUSINESSPARTNERASupplierTypeCreateFromJSONTyped,
    APIBUSINESSPARTNERASupplierTypeCreateToJSON,
} from './APIBUSINESSPARTNERASupplierTypeCreate';
import type { APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate } from './APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate';
import {
    APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreateFromJSON,
    APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreateFromJSONTyped,
    APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreateToJSON,
} from './APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate';
import type { BillExLimit } from './BillExLimit';
import {
    BillExLimitFromJSON,
    BillExLimitFromJSONTyped,
    BillExLimitToJSON,
} from './BillExLimit';
import type { CheckCashingTime } from './CheckCashingTime';
import {
    CheckCashingTimeFromJSON,
    CheckCashingTimeFromJSONTyped,
    CheckCashingTimeToJSON,
} from './CheckCashingTime';

/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERASupplierCompanyTypeCreate
 */
export interface APIBUSINESSPARTNERASupplierCompanyTypeCreate {
    /**
     * Account Number of Supplier
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplier: string;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    companyCode: string;
    /**
     * Authorization Group
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    authorizationGroup?: string | null;
    /**
     * Block Key for Payment
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    paymentBlockingReason?: string | null;
    /**
     * Posting block for company code
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierIsBlockedForPosting?: boolean | null;
    /**
     * Accounting Clerk Abbreviation
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    accountingClerk?: string | null;
    /**
     * Accounting clerk's fax number at the customer/vendor
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    accountingClerkFaxNumber?: string | null;
    /**
     * Accounting clerk's telephone number at business partner
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    accountingClerkPhoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierClerk?: string | null;
    /**
     * Internet address of partner company clerk
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierClerkURL?: string | null;
    /**
     * List of Respected Payment Methods
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    paymentMethodsList?: string | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    paymentReason?: string | null;
    /**
     * Key for Terms of Payment
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    paymentTerms?: string | null;
    /**
     * Indicator: Clearing between customer and vendor?
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    clearCustomerSupplier?: boolean | null;
    /**
     * Indicator: Local Processing?
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    isToBeLocallyProcessed?: boolean | null;
    /**
     * Indicator: Pay All Items Separately?
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    itemIsToBePaidSeparately?: boolean | null;
    /**
     * Indicator: Send Payment Advices by EDI
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    paymentIsToBeSentByEDI?: boolean | null;
    /**
     * Short Key for a House Bank
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    houseBank?: string | null;
    /**
     * 
     * @type {CheckCashingTime}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    checkPaidDurationInDays?: CheckCashingTime | null;
    /**
     * Currency Key
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    currency?: string | null;
    /**
     * 
     * @type {BillExLimit}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    billOfExchLmtAmtInCoCodeCrcy?: BillExLimit | null;
    /**
     * Our account number with the vendor
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierClerkIDBySupplier?: string | null;
    /**
     * Reconciliation Account in General Ledger
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    reconciliationAccount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    interestCalculationCode?: string | null;
    /**
     * Key Date of Last Interest Calculation
     * @type {Date}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    interestCalculationDate?: Date | null;
    /**
     * Interest Calculation Frequency in Months
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    intrstCalcFrequencyInMonths?: string | null;
    /**
     * Head Office Account Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierHeadOffice?: string | null;
    /**
     * Account number of the alternative payee
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    alternativePayee?: string | null;
    /**
     * Key for Sorting According to Assignment Numbers
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    layoutSortingRule?: string | null;
    /**
     * Tolerance Group for Business Partner/G/L Account
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    aPARToleranceGroup?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierCertificationDate?: Date | null;
    /**
     * Memo
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierAccountNote?: string | null;
    /**
     * Withholding Tax Country/Region Key
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    withholdingTaxCountry?: string | null;
    /**
     * Deletion Flag for Master Record (Company Code Level)
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    deletionIndicator?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    cashPlanningGroup?: string | null;
    /**
     * Check Flag for Double Invoices or Credit Memos
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    isToBeCheckedForDuplicates?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    minorityGroup?: string | null;
    /**
     * Supplier Account Group
     * @type {string}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    supplierAccountGroup?: string | null;
    /**
     * 
     * @type {Array<APIBUSINESSPARTNERASupplierCompanyTextTypeCreate>}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    toCompanyText?: Array<APIBUSINESSPARTNERASupplierCompanyTextTypeCreate>;
    /**
     * 
     * @type {APIBUSINESSPARTNERASupplierTypeCreate}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    toSupplier?: APIBUSINESSPARTNERASupplierTypeCreate;
    /**
     * 
     * @type {Array<APIBUSINESSPARTNERASupplierDunningTypeCreate>}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    toSupplierDunning?: Array<APIBUSINESSPARTNERASupplierDunningTypeCreate>;
    /**
     * 
     * @type {Array<APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate>}
     * @memberof APIBUSINESSPARTNERASupplierCompanyTypeCreate
     */
    toSupplierWithHoldingTax?: Array<APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate>;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERASupplierCompanyTypeCreate interface.
 */
export function instanceOfAPIBUSINESSPARTNERASupplierCompanyTypeCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "supplier" in value;
    isInstance = isInstance && "companyCode" in value;

    return isInstance;
}

export function APIBUSINESSPARTNERASupplierCompanyTypeCreateFromJSON(json: any): APIBUSINESSPARTNERASupplierCompanyTypeCreate {
    return APIBUSINESSPARTNERASupplierCompanyTypeCreateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERASupplierCompanyTypeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERASupplierCompanyTypeCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'supplier': json['Supplier'],
        'companyCode': json['CompanyCode'],
        'authorizationGroup': !exists(json, 'AuthorizationGroup') ? undefined : json['AuthorizationGroup'],
        'paymentBlockingReason': !exists(json, 'PaymentBlockingReason') ? undefined : json['PaymentBlockingReason'],
        'supplierIsBlockedForPosting': !exists(json, 'SupplierIsBlockedForPosting') ? undefined : json['SupplierIsBlockedForPosting'],
        'accountingClerk': !exists(json, 'AccountingClerk') ? undefined : json['AccountingClerk'],
        'accountingClerkFaxNumber': !exists(json, 'AccountingClerkFaxNumber') ? undefined : json['AccountingClerkFaxNumber'],
        'accountingClerkPhoneNumber': !exists(json, 'AccountingClerkPhoneNumber') ? undefined : json['AccountingClerkPhoneNumber'],
        'supplierClerk': !exists(json, 'SupplierClerk') ? undefined : json['SupplierClerk'],
        'supplierClerkURL': !exists(json, 'SupplierClerkURL') ? undefined : json['SupplierClerkURL'],
        'paymentMethodsList': !exists(json, 'PaymentMethodsList') ? undefined : json['PaymentMethodsList'],
        'paymentReason': !exists(json, 'PaymentReason') ? undefined : json['PaymentReason'],
        'paymentTerms': !exists(json, 'PaymentTerms') ? undefined : json['PaymentTerms'],
        'clearCustomerSupplier': !exists(json, 'ClearCustomerSupplier') ? undefined : json['ClearCustomerSupplier'],
        'isToBeLocallyProcessed': !exists(json, 'IsToBeLocallyProcessed') ? undefined : json['IsToBeLocallyProcessed'],
        'itemIsToBePaidSeparately': !exists(json, 'ItemIsToBePaidSeparately') ? undefined : json['ItemIsToBePaidSeparately'],
        'paymentIsToBeSentByEDI': !exists(json, 'PaymentIsToBeSentByEDI') ? undefined : json['PaymentIsToBeSentByEDI'],
        'houseBank': !exists(json, 'HouseBank') ? undefined : json['HouseBank'],
        'checkPaidDurationInDays': !exists(json, 'CheckPaidDurationInDays') ? undefined : CheckCashingTimeFromJSON(json['CheckPaidDurationInDays']),
        'currency': !exists(json, 'Currency') ? undefined : json['Currency'],
        'billOfExchLmtAmtInCoCodeCrcy': !exists(json, 'BillOfExchLmtAmtInCoCodeCrcy') ? undefined : BillExLimitFromJSON(json['BillOfExchLmtAmtInCoCodeCrcy']),
        'supplierClerkIDBySupplier': !exists(json, 'SupplierClerkIDBySupplier') ? undefined : json['SupplierClerkIDBySupplier'],
        'reconciliationAccount': !exists(json, 'ReconciliationAccount') ? undefined : json['ReconciliationAccount'],
        'interestCalculationCode': !exists(json, 'InterestCalculationCode') ? undefined : json['InterestCalculationCode'],
        'interestCalculationDate': !exists(json, 'InterestCalculationDate') ? undefined : (json['InterestCalculationDate'] === null ? null : new Date(json['InterestCalculationDate'])),
        'intrstCalcFrequencyInMonths': !exists(json, 'IntrstCalcFrequencyInMonths') ? undefined : json['IntrstCalcFrequencyInMonths'],
        'supplierHeadOffice': !exists(json, 'SupplierHeadOffice') ? undefined : json['SupplierHeadOffice'],
        'alternativePayee': !exists(json, 'AlternativePayee') ? undefined : json['AlternativePayee'],
        'layoutSortingRule': !exists(json, 'LayoutSortingRule') ? undefined : json['LayoutSortingRule'],
        'aPARToleranceGroup': !exists(json, 'APARToleranceGroup') ? undefined : json['APARToleranceGroup'],
        'supplierCertificationDate': !exists(json, 'SupplierCertificationDate') ? undefined : (json['SupplierCertificationDate'] === null ? null : new Date(json['SupplierCertificationDate'])),
        'supplierAccountNote': !exists(json, 'SupplierAccountNote') ? undefined : json['SupplierAccountNote'],
        'withholdingTaxCountry': !exists(json, 'WithholdingTaxCountry') ? undefined : json['WithholdingTaxCountry'],
        'deletionIndicator': !exists(json, 'DeletionIndicator') ? undefined : json['DeletionIndicator'],
        'cashPlanningGroup': !exists(json, 'CashPlanningGroup') ? undefined : json['CashPlanningGroup'],
        'isToBeCheckedForDuplicates': !exists(json, 'IsToBeCheckedForDuplicates') ? undefined : json['IsToBeCheckedForDuplicates'],
        'minorityGroup': !exists(json, 'MinorityGroup') ? undefined : json['MinorityGroup'],
        'supplierAccountGroup': !exists(json, 'SupplierAccountGroup') ? undefined : json['SupplierAccountGroup'],
        'toCompanyText': !exists(json, 'to_CompanyText') ? undefined : ((json['to_CompanyText'] as Array<any>).map(APIBUSINESSPARTNERASupplierCompanyTextTypeCreateFromJSON)),
        'toSupplier': !exists(json, 'to_Supplier') ? undefined : APIBUSINESSPARTNERASupplierTypeCreateFromJSON(json['to_Supplier']),
        'toSupplierDunning': !exists(json, 'to_SupplierDunning') ? undefined : ((json['to_SupplierDunning'] as Array<any>).map(APIBUSINESSPARTNERASupplierDunningTypeCreateFromJSON)),
        'toSupplierWithHoldingTax': !exists(json, 'to_SupplierWithHoldingTax') ? undefined : ((json['to_SupplierWithHoldingTax'] as Array<any>).map(APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreateFromJSON)),
    };
}

export function APIBUSINESSPARTNERASupplierCompanyTypeCreateToJSON(value?: APIBUSINESSPARTNERASupplierCompanyTypeCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Supplier': value.supplier,
        'CompanyCode': value.companyCode,
        'AuthorizationGroup': value.authorizationGroup,
        'PaymentBlockingReason': value.paymentBlockingReason,
        'SupplierIsBlockedForPosting': value.supplierIsBlockedForPosting,
        'AccountingClerk': value.accountingClerk,
        'AccountingClerkFaxNumber': value.accountingClerkFaxNumber,
        'AccountingClerkPhoneNumber': value.accountingClerkPhoneNumber,
        'SupplierClerk': value.supplierClerk,
        'SupplierClerkURL': value.supplierClerkURL,
        'PaymentMethodsList': value.paymentMethodsList,
        'PaymentReason': value.paymentReason,
        'PaymentTerms': value.paymentTerms,
        'ClearCustomerSupplier': value.clearCustomerSupplier,
        'IsToBeLocallyProcessed': value.isToBeLocallyProcessed,
        'ItemIsToBePaidSeparately': value.itemIsToBePaidSeparately,
        'PaymentIsToBeSentByEDI': value.paymentIsToBeSentByEDI,
        'HouseBank': value.houseBank,
        'CheckPaidDurationInDays': CheckCashingTimeToJSON(value.checkPaidDurationInDays),
        'Currency': value.currency,
        'BillOfExchLmtAmtInCoCodeCrcy': BillExLimitToJSON(value.billOfExchLmtAmtInCoCodeCrcy),
        'SupplierClerkIDBySupplier': value.supplierClerkIDBySupplier,
        'ReconciliationAccount': value.reconciliationAccount,
        'InterestCalculationCode': value.interestCalculationCode,
        'InterestCalculationDate': value.interestCalculationDate === undefined ? undefined : (value.interestCalculationDate === null ? null : value.interestCalculationDate.toISOString().substring(0,10)),
        'IntrstCalcFrequencyInMonths': value.intrstCalcFrequencyInMonths,
        'SupplierHeadOffice': value.supplierHeadOffice,
        'AlternativePayee': value.alternativePayee,
        'LayoutSortingRule': value.layoutSortingRule,
        'APARToleranceGroup': value.aPARToleranceGroup,
        'SupplierCertificationDate': value.supplierCertificationDate === undefined ? undefined : (value.supplierCertificationDate === null ? null : value.supplierCertificationDate.toISOString().substring(0,10)),
        'SupplierAccountNote': value.supplierAccountNote,
        'WithholdingTaxCountry': value.withholdingTaxCountry,
        'DeletionIndicator': value.deletionIndicator,
        'CashPlanningGroup': value.cashPlanningGroup,
        'IsToBeCheckedForDuplicates': value.isToBeCheckedForDuplicates,
        'MinorityGroup': value.minorityGroup,
        'SupplierAccountGroup': value.supplierAccountGroup,
        'to_CompanyText': value.toCompanyText === undefined ? undefined : ((value.toCompanyText as Array<any>).map(APIBUSINESSPARTNERASupplierCompanyTextTypeCreateToJSON)),
        'to_Supplier': APIBUSINESSPARTNERASupplierTypeCreateToJSON(value.toSupplier),
        'to_SupplierDunning': value.toSupplierDunning === undefined ? undefined : ((value.toSupplierDunning as Array<any>).map(APIBUSINESSPARTNERASupplierDunningTypeCreateToJSON)),
        'to_SupplierWithHoldingTax': value.toSupplierWithHoldingTax === undefined ? undefined : ((value.toSupplierWithHoldingTax as Array<any>).map(APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreateToJSON)),
    };
}

