/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
 */
export interface APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate {
    /**
     * Country/Region for Telephone/Fax Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    destinationLocationCountry?: string | null;
    /**
     * Data element for domain BOOLE: TRUE (='X') and FALSE (=' ')
     * @type {boolean}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    isDefaultPhoneNumber?: boolean | null;
    /**
     * Telephone No.: Dialing Code and Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    phoneNumber?: string | null;
    /**
     * Telephone no.: Extension
     * @type {string}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    phoneNumberExtension?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    validityStartDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
     */
    validityEndDate?: Date | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate interface.
 */
export function instanceOfAPIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdateFromJSON(json: any): APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate {
    return APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'destinationLocationCountry': !exists(json, 'DestinationLocationCountry') ? undefined : json['DestinationLocationCountry'],
        'isDefaultPhoneNumber': !exists(json, 'IsDefaultPhoneNumber') ? undefined : json['IsDefaultPhoneNumber'],
        'phoneNumber': !exists(json, 'PhoneNumber') ? undefined : json['PhoneNumber'],
        'phoneNumberExtension': !exists(json, 'PhoneNumberExtension') ? undefined : json['PhoneNumberExtension'],
        'validityStartDate': !exists(json, 'ValidityStartDate') ? undefined : (json['ValidityStartDate'] === null ? null : new Date(json['ValidityStartDate'])),
        'validityEndDate': !exists(json, 'ValidityEndDate') ? undefined : (json['ValidityEndDate'] === null ? null : new Date(json['ValidityEndDate'])),
    };
}

export function APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdateToJSON(value?: APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DestinationLocationCountry': value.destinationLocationCountry,
        'IsDefaultPhoneNumber': value.isDefaultPhoneNumber,
        'PhoneNumber': value.phoneNumber,
        'PhoneNumberExtension': value.phoneNumberExtension,
        'ValidityStartDate': value.validityStartDate === undefined ? undefined : (value.validityStartDate === null ? null : value.validityStartDate.toISOString().substring(0,10)),
        'ValidityEndDate': value.validityEndDate === undefined ? undefined : (value.validityEndDate === null ? null : value.validityEndDate.toISOString().substring(0,10)),
    };
}

