/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate
 */
export interface APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate {
    /**
     * Bank Keys
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate
     */
    bankKey?: string | null;
    /**
     * Bank Country/Region Key
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate
     */
    bankCountry?: string | null;
    /**
     * Minimum Reserve Requirement for Bank
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate
     */
    bPMinimumReserve?: string | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate interface.
 */
export function instanceOfAPIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdateFromJSON(json: any): APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate {
    return APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bankKey': !exists(json, 'BankKey') ? undefined : json['BankKey'],
        'bankCountry': !exists(json, 'BankCountry') ? undefined : json['BankCountry'],
        'bPMinimumReserve': !exists(json, 'BPMinimumReserve') ? undefined : json['BPMinimumReserve'],
    };
}

export function APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdateToJSON(value?: APIBUSINESSPARTNERABusinessPartnerIsBankTypeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BankKey': value.bankKey,
        'BankCountry': value.bankCountry,
        'BPMinimumReserve': value.bPMinimumReserve,
    };
}

