/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate
 */
export interface APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate {
    /**
     * Seller-Defined Customer Address ID for EDI
     * @type {string}
     * @memberof APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate
     */
    customerExternalRefID?: string | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate interface.
 */
export function instanceOfAPIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdateFromJSON(json: any): APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate {
    return APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerExternalRefID': !exists(json, 'CustomerExternalRefID') ? undefined : json['CustomerExternalRefID'],
    };
}

export function APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdateToJSON(value?: APIBUSINESSPARTNERACustAddrDepdntExtIdentifierTypeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CustomerExternalRefID': value.customerExternalRefID,
    };
}

