/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
 */
export interface APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate {
    /**
     * Business Partner Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
     */
    businessPartner: string;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
     */
    businessPartnerRole: string;
    /**
     * Validity Start of a BP Role
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
     */
    validFrom?: Date | null;
    /**
     * Validity End of a BP Role
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
     */
    validTo?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate
     */
    authorizationGroup?: string | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate interface.
 */
export function instanceOfAPIBUSINESSPARTNERABusinessPartnerRoleTypeCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "businessPartner" in value;
    isInstance = isInstance && "businessPartnerRole" in value;

    return isInstance;
}

export function APIBUSINESSPARTNERABusinessPartnerRoleTypeCreateFromJSON(json: any): APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate {
    return APIBUSINESSPARTNERABusinessPartnerRoleTypeCreateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERABusinessPartnerRoleTypeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessPartner': json['BusinessPartner'],
        'businessPartnerRole': json['BusinessPartnerRole'],
        'validFrom': !exists(json, 'ValidFrom') ? undefined : (json['ValidFrom'] === null ? null : new Date(json['ValidFrom'])),
        'validTo': !exists(json, 'ValidTo') ? undefined : (json['ValidTo'] === null ? null : new Date(json['ValidTo'])),
        'authorizationGroup': !exists(json, 'AuthorizationGroup') ? undefined : json['AuthorizationGroup'],
    };
}

export function APIBUSINESSPARTNERABusinessPartnerRoleTypeCreateToJSON(value?: APIBUSINESSPARTNERABusinessPartnerRoleTypeCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BusinessPartner': value.businessPartner,
        'BusinessPartnerRole': value.businessPartnerRole,
        'ValidFrom': value.validFrom === undefined ? undefined : (value.validFrom === null ? null : value.validFrom.toISOString()),
        'ValidTo': value.validTo === undefined ? undefined : (value.validTo === null ? null : value.validTo.toISOString()),
        'AuthorizationGroup': value.authorizationGroup,
    };
}

