/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
 */
export interface APIBUSINESSPARTNERABuPaIdentificationTypeUpdate {
    /**
     * Responsible Institution for ID Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    bPIdnNmbrIssuingInstitute?: string | null;
    /**
     * Date of Entry for ID Number
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    bPIdentificationEntryDate?: Date | null;
    /**
     * Country/Region in Which ID Number is Valid or Was Assigned
     * @type {string}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    country?: string | null;
    /**
     * Region (State, Province, County)
     * @type {string}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    region?: string | null;
    /**
     * Validity Start for ID Number
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    validityStartDate?: Date | null;
    /**
     * Validity End for ID Number
     * @type {Date}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    validityEndDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERABuPaIdentificationTypeUpdate
     */
    authorizationGroup?: string | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERABuPaIdentificationTypeUpdate interface.
 */
export function instanceOfAPIBUSINESSPARTNERABuPaIdentificationTypeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIBUSINESSPARTNERABuPaIdentificationTypeUpdateFromJSON(json: any): APIBUSINESSPARTNERABuPaIdentificationTypeUpdate {
    return APIBUSINESSPARTNERABuPaIdentificationTypeUpdateFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERABuPaIdentificationTypeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERABuPaIdentificationTypeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bPIdnNmbrIssuingInstitute': !exists(json, 'BPIdnNmbrIssuingInstitute') ? undefined : json['BPIdnNmbrIssuingInstitute'],
        'bPIdentificationEntryDate': !exists(json, 'BPIdentificationEntryDate') ? undefined : (json['BPIdentificationEntryDate'] === null ? null : new Date(json['BPIdentificationEntryDate'])),
        'country': !exists(json, 'Country') ? undefined : json['Country'],
        'region': !exists(json, 'Region') ? undefined : json['Region'],
        'validityStartDate': !exists(json, 'ValidityStartDate') ? undefined : (json['ValidityStartDate'] === null ? null : new Date(json['ValidityStartDate'])),
        'validityEndDate': !exists(json, 'ValidityEndDate') ? undefined : (json['ValidityEndDate'] === null ? null : new Date(json['ValidityEndDate'])),
        'authorizationGroup': !exists(json, 'AuthorizationGroup') ? undefined : json['AuthorizationGroup'],
    };
}

export function APIBUSINESSPARTNERABuPaIdentificationTypeUpdateToJSON(value?: APIBUSINESSPARTNERABuPaIdentificationTypeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BPIdnNmbrIssuingInstitute': value.bPIdnNmbrIssuingInstitute,
        'BPIdentificationEntryDate': value.bPIdentificationEntryDate === undefined ? undefined : (value.bPIdentificationEntryDate === null ? null : value.bPIdentificationEntryDate.toISOString().substring(0,10)),
        'Country': value.country,
        'Region': value.region,
        'ValidityStartDate': value.validityStartDate === undefined ? undefined : (value.validityStartDate === null ? null : value.validityStartDate.toISOString().substring(0,10)),
        'ValidityEndDate': value.validityEndDate === undefined ? undefined : (value.validityEndDate === null ? null : value.validityEndDate.toISOString().substring(0,10)),
        'AuthorizationGroup': value.authorizationGroup,
    };
}

