/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIBUSINESSPARTNERABusinessPartnerTaxNumberType
 */
export interface APIBUSINESSPARTNERABusinessPartnerTaxNumberType {
    /**
     * Business Partner Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerTaxNumberType
     */
    businessPartner?: string;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerTaxNumberType
     */
    bPTaxType?: string;
    /**
     * Business Partner Tax Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerTaxNumberType
     */
    bPTaxNumber?: string | null;
    /**
     * Business Partner Tax Number
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerTaxNumberType
     */
    bPTaxLongNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof APIBUSINESSPARTNERABusinessPartnerTaxNumberType
     */
    authorizationGroup?: string | null;
}

/**
 * Check if a given object implements the APIBUSINESSPARTNERABusinessPartnerTaxNumberType interface.
 */
export function instanceOfAPIBUSINESSPARTNERABusinessPartnerTaxNumberType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIBUSINESSPARTNERABusinessPartnerTaxNumberTypeFromJSON(json: any): APIBUSINESSPARTNERABusinessPartnerTaxNumberType {
    return APIBUSINESSPARTNERABusinessPartnerTaxNumberTypeFromJSONTyped(json, false);
}

export function APIBUSINESSPARTNERABusinessPartnerTaxNumberTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBUSINESSPARTNERABusinessPartnerTaxNumberType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessPartner': !exists(json, 'BusinessPartner') ? undefined : json['BusinessPartner'],
        'bPTaxType': !exists(json, 'BPTaxType') ? undefined : json['BPTaxType'],
        'bPTaxNumber': !exists(json, 'BPTaxNumber') ? undefined : json['BPTaxNumber'],
        'bPTaxLongNumber': !exists(json, 'BPTaxLongNumber') ? undefined : json['BPTaxLongNumber'],
        'authorizationGroup': !exists(json, 'AuthorizationGroup') ? undefined : json['AuthorizationGroup'],
    };
}

export function APIBUSINESSPARTNERABusinessPartnerTaxNumberTypeToJSON(value?: APIBUSINESSPARTNERABusinessPartnerTaxNumberType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BusinessPartner': value.businessPartner,
        'BPTaxType': value.bPTaxType,
        'BPTaxNumber': value.bPTaxNumber,
        'BPTaxLongNumber': value.bPTaxLongNumber,
        'AuthorizationGroup': value.authorizationGroup,
    };
}

