/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Amount of Balance Sheet Total for Company
 * @export
 * @interface BalanceSheetTotal
 */
export interface BalanceSheetTotal {
}

/**
 * Check if a given object implements the BalanceSheetTotal interface.
 */
export function instanceOfBalanceSheetTotal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BalanceSheetTotalFromJSON(json: any): BalanceSheetTotal {
    return BalanceSheetTotalFromJSONTyped(json, false);
}

export function BalanceSheetTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceSheetTotal {
    return json;
}

export function BalanceSheetTotalToJSON(value?: BalanceSheetTotal | null): any {
    return value;
}

