/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { APIBUSINESSPARTNERABPContactToFuncAndDeptType } from './APIBUSINESSPARTNERABPContactToFuncAndDeptType';
import {
    APIBUSINESSPARTNERABPContactToFuncAndDeptTypeFromJSON,
    APIBUSINESSPARTNERABPContactToFuncAndDeptTypeFromJSONTyped,
    APIBUSINESSPARTNERABPContactToFuncAndDeptTypeToJSON,
} from './APIBUSINESSPARTNERABPContactToFuncAndDeptType';
import type { Count } from './Count';
import {
    CountFromJSON,
    CountFromJSONTyped,
    CountToJSON,
} from './Count';

/**
 * 
 * @export
 * @interface CollectionOfABPContactToFuncAndDeptType
 */
export interface CollectionOfABPContactToFuncAndDeptType {
    /**
     * 
     * @type {Count}
     * @memberof CollectionOfABPContactToFuncAndDeptType
     */
    count?: Count;
    /**
     * 
     * @type {Array<APIBUSINESSPARTNERABPContactToFuncAndDeptType>}
     * @memberof CollectionOfABPContactToFuncAndDeptType
     */
    value?: Array<APIBUSINESSPARTNERABPContactToFuncAndDeptType>;
}

/**
 * Check if a given object implements the CollectionOfABPContactToFuncAndDeptType interface.
 */
export function instanceOfCollectionOfABPContactToFuncAndDeptType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CollectionOfABPContactToFuncAndDeptTypeFromJSON(json: any): CollectionOfABPContactToFuncAndDeptType {
    return CollectionOfABPContactToFuncAndDeptTypeFromJSONTyped(json, false);
}

export function CollectionOfABPContactToFuncAndDeptTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionOfABPContactToFuncAndDeptType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, '@count') ? undefined : CountFromJSON(json['@count']),
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>).map(APIBUSINESSPARTNERABPContactToFuncAndDeptTypeFromJSON)),
    };
}

export function CollectionOfABPContactToFuncAndDeptTypeToJSON(value?: CollectionOfABPContactToFuncAndDeptType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@count': CountToJSON(value.count),
        'value': value.value === undefined ? undefined : ((value.value as Array<any>).map(APIBUSINESSPARTNERABPContactToFuncAndDeptTypeToJSON)),
    };
}

