/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { APIBUSINESSPARTNERABPFinancialServicesReportingType } from './APIBUSINESSPARTNERABPFinancialServicesReportingType';
import {
    APIBUSINESSPARTNERABPFinancialServicesReportingTypeFromJSON,
    APIBUSINESSPARTNERABPFinancialServicesReportingTypeFromJSONTyped,
    APIBUSINESSPARTNERABPFinancialServicesReportingTypeToJSON,
} from './APIBUSINESSPARTNERABPFinancialServicesReportingType';
import type { Count } from './Count';
import {
    CountFromJSON,
    CountFromJSONTyped,
    CountToJSON,
} from './Count';

/**
 * 
 * @export
 * @interface CollectionOfABPFinancialServicesReportingType
 */
export interface CollectionOfABPFinancialServicesReportingType {
    /**
     * 
     * @type {Count}
     * @memberof CollectionOfABPFinancialServicesReportingType
     */
    count?: Count;
    /**
     * 
     * @type {Array<APIBUSINESSPARTNERABPFinancialServicesReportingType>}
     * @memberof CollectionOfABPFinancialServicesReportingType
     */
    value?: Array<APIBUSINESSPARTNERABPFinancialServicesReportingType>;
}

/**
 * Check if a given object implements the CollectionOfABPFinancialServicesReportingType interface.
 */
export function instanceOfCollectionOfABPFinancialServicesReportingType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CollectionOfABPFinancialServicesReportingTypeFromJSON(json: any): CollectionOfABPFinancialServicesReportingType {
    return CollectionOfABPFinancialServicesReportingTypeFromJSONTyped(json, false);
}

export function CollectionOfABPFinancialServicesReportingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionOfABPFinancialServicesReportingType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, '@count') ? undefined : CountFromJSON(json['@count']),
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>).map(APIBUSINESSPARTNERABPFinancialServicesReportingTypeFromJSON)),
    };
}

export function CollectionOfABPFinancialServicesReportingTypeToJSON(value?: CollectionOfABPFinancialServicesReportingType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@count': CountToJSON(value.count),
        'value': value.value === undefined ? undefined : ((value.value as Array<any>).map(APIBUSINESSPARTNERABPFinancialServicesReportingTypeToJSON)),
    };
}

