/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrossPremium
 */
export interface GrossPremium {
}

/**
 * Check if a given object implements the GrossPremium interface.
 */
export function instanceOfGrossPremium(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GrossPremiumFromJSON(json: any): GrossPremium {
    return GrossPremiumFromJSONTyped(json, false);
}

export function GrossPremiumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrossPremium {
    return json;
}

export function GrossPremiumToJSON(value?: GrossPremium | null): any {
    return value;
}

