/* tslint:disable */
/* eslint-disable */
/**
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Amount of Issued Stock Capital for Company
 * @export
 * @interface IssuedStockCapital
 */
export interface IssuedStockCapital {
}

/**
 * Check if a given object implements the IssuedStockCapital interface.
 */
export function instanceOfIssuedStockCapital(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IssuedStockCapitalFromJSON(json: any): IssuedStockCapital {
    return IssuedStockCapitalFromJSONTyped(json, false);
}

export function IssuedStockCapitalFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuedStockCapital {
    return json;
}

export function IssuedStockCapitalToJSON(value?: IssuedStockCapital | null): any {
    return value;
}

